Controllers/CourseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppwithAdo.Models;

namespace WebAppwithAdo.Controllers
{
    public class CourseController : Controller
    {
        CourseDAL cd = new CourseDAL();
        public IActionResult List()
        {
            ViewBag.CourseList = cd.GetAllCourse();
            return View();
        }
        public IActionResult AddNewCourse()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddNewCourse(IFormCollection form)
        {
            Course c = new Course();
            c.Name = form["name"];
            c.Fees = Convert.ToSingle(form["Fees"]);
            int result = cd.Save(c);
            if (result == 1)
            {

                return RedirectToAction("List");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Course c = cd.GetCourseById(id);
            ViewBag.Id = c.Id;
            ViewBag.Name = c.Name;
            ViewBag.Fees = c.Fees;
            return View();
        }
        [HttpPost]
        public IActionResult Edit(IFormCollection form)
        {
            Course c = new Course();
            c.Id = Convert.ToInt32(form["id"]);
            c.Name = form["Name"].ToString();
            c.Fees = Convert.ToSingle(form["Fees"]);
            int res = cd.Update(c);
            if (res == 1)
            {
                return RedirectToAction("List");
            }

            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Course c = cd.GetCourseById(id);
            ViewBag.Id = c.Id;
            ViewBag.Name = c.Name;
            ViewBag.Fees = c.Fees;
            return View();
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            int res = cd.Delete(id);
            if (res == 1)
            {
                return RedirectToAction("List");
            }
            else
                return View();
        }
    }   
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppwithAdo.Models;

namespace WebAppwithAdo.Controllers
{
    public class EmployeeController : Controller
    {
        EmployeeAdd emp = new EmployeeAdd();

        public IActionResult List()
        {
            ViewBag.EmployeeList = emp.GetAllProducts();
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(IFormCollection form)
        {
            Employee p = new Employee();
            p.Name = form["Name"];
            p.Salary = Convert.ToSingle(form["salary"]);
            int res = emp.Save(p);
            if (res == 1)
            {

                return RedirectToAction("List");

            }
            return View();

        }
        [HttpGet]
        public IActionResult Edit(int id) 
        {
            Employee prod = emp.GetProductById(id);
            ViewBag.Name = prod.Name;
            ViewBag.Salary = prod.Salary;
            ViewBag.Id = prod.Id;
            return View();

        }
        [HttpPost]
        public IActionResult Edit(IFormCollection form)
        {
            Employee prod = new Employee();
            prod.Name = form["Name"];
            prod.Salary = Convert.ToSingle(form["salary"]);
            prod.Id = Convert.ToInt32(form["id"]);
            int res = emp.update(prod);
            if (res == 1)
            {
                return RedirectToAction("List");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Employee prod = emp.GetProductById(id);
            ViewBag.Name = prod.Name;
            ViewBag.Salary = prod.Salary;
            ViewBag.Id = prod.Id;
            return View();
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            int res = emp.Delete(id);
            if (res == 1)
            {
                return RedirectToAction("List");

            }
            return View();
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppwithAdo.Models;

namespace WebAppwithAdo.Controllers
{
    public class ProductController : Controller
    {
        ProductDAL context = new ProductDAL();
        public IActionResult List()
        {
            ViewBag.ProductList = context.GetAllProducts();
           
            return View();

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(IFormCollection form)
        {
            Product p = new Product();
            p.Name = form["Name"];
            p.Price = Convert.ToSingle(form["price"]);
            int res = context.Save(p);
            if(res==1)
            {
                
                return RedirectToAction("List");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Product prod = context.GetProductById(id);
            ViewBag.Name = prod.Name;
            ViewBag.Price = prod.Price;
            ViewBag.Id = prod.Id;
            return View();
        }
        [HttpPost]
        public IActionResult Edit(IFormCollection form)
        {
            Product prod = new Product();
            prod.Name = form["Name"];
            prod.Price = Convert.ToSingle(form["price"]);
            prod.Id = Convert.ToInt32(form["id"]);
            int res = context.update(prod);
            if(res==1)
            {
                return RedirectToAction("List");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Product prod = context.GetProductById(id);
            ViewBag.Name = prod.Name;
            ViewBag.Price = prod.Price;
            ViewBag.Id = prod.Id;
            return View();
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            int res = context.Delete(id);
            if(res==1)
            {
                return RedirectToAction("List");

            }
            return View();
        }


    }
}

Controllers/ProductWithModelController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppwithAdo;
using WebAppwithAdo.Models;

namespace WebAppwithAdo.Controllers
{
    public class ProductWithModelController : Controller
    {
        ProductDAL db = new ProductDAL();
        // GET: ProductWithModelController
        public ActionResult Index()
        {
            var model = db.GetAllProducts();
            return View(model);
        }

        // GET: ProductWithModelController/Details/5
        public ActionResult Details(int id)
        {
            Product prod = db.GetProductById(id);
            return View(prod);
        }

        // GET: ProductWithModelController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductWithModelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product prod)
        {
            try
            {
                db.Save(prod);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductWithModelController/Edit/5
        public ActionResult Edit(int id)
        {
            Product prod = db.GetProductById(id);
            return View(prod);
        }

        // POST: ProductWithModelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product prod)
        {
            try
            {
                db.update(prod);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductWithModelController/Delete/5
        public ActionResult Delete(int id)
        {
            Product prod = db.GetProductById(id);
            return View(prod);
        }

        // POST: ProductWithModelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            int res = db.Delete(id);
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppwithAdo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppwithAdo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Create">Add Product</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="List">Employee List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Create">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductWithModel" asp-action="Index">Product1 List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="List">Course List</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAppwithAdo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>